### ISSUE TITLE
Theme doesn't build on gitbook.com

### ISSUE THREAD

**Issue by lucianalml** [willin/gitbook-plugin-theme-material#1]
I'm trying to upload a book with theme material to gitbook.com but it's not building. 
Locally it was working fine but uploading to Gitbook it is not building...

The output of the build is:

Downloading source
Pulling from S3
Extracting source
GitBook version is 3.2.2
Tweaking book.json
Installing plugins
info: installing 2 plugins using npm@3.9.2 
info: 
info: installing plugin "theme-material" 
info: install plugin "theme-material" (*) from NPM with version 1.0.2 
cp: cannot stat ‘node_modules/materialize-css/js/date_picker/picker.js’: No such file or directory

Error: gitbook-plugin-theme-material@1.0.2 postinstall: `cp node_modules/materialize-css/js/date_picker/picker.js node_modules/materialize-css/bin`
Exit status 1

Thanks,

Luciana

**Comment by willin** [comment]
i will look into it.
